extends:
    [
        "stylelint-config-standard",
        "stylelint-config-prettier",
        "stylelint-prettier/recommended",
        "stylelint-config-standard-scss",
    ]
rules:
    {
        alpha-value-notation: null,
        color-hex-length: null,
        rule-empty-line-before: null,
        color-function-notation: null,
        selector-class-pattern: null,
        font-family-name-quotes: null,
        declaration-block-no-duplicate-properties: null,
        font-family-no-missing-generic-family-keyword: null,
        selector-anb-no-unmatchable: null,
    }
